# Generated by Django 4.1.4 on 2022-12-29 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content4',
            field=models.TextField(default=datetime.datetime(2022, 12, 29, 18, 41, 21, 924762, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
