# Generated by Django 4.1.4 on 2022-12-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0002_post_content4_post_content5'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content6',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
